name: CI

on: [push, pull_request]

jobs:
  job_build:
    name: Compilation
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: |
          make DEBUG=0 COIN=bitcoin && mv bin/ bitcoin-bin/
          make clean
          make DEBUG=0 COIN=bitcoin_testnet && mv bin/ bitcoin-testnet-bin/
          make clean
          make DEBUG=0 COIN=bitcoin_testnet_lib && mv bin/ bitcoin-testnet-lib-bin/
      - name: Upload Bitcoin app binary
        uses: actions/upload-artifact@v2
        with:
          name: bitcoin-app
          path: bitcoin-bin

      - name: Upload Bitcoin Testnet app binary
        uses: actions/upload-artifact@v2
        with:
          name: bitcoin-testnet-app
          path: bitcoin-testnet-bin

      - name: Upload Bitcoin Testnet app binary (lib version)
        uses: actions/upload-artifact@v2
        with:
          name: bitcoin-testnet-lib-app
          path: bitcoin-testnet-lib-bin


  job_test:
    name: Tests
    needs: job_build
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/speculos:latest
      ports:
        - 1234:1234
        - 9999:9999
        - 40000:40000
        - 41000:41000
        - 42000:42000
        - 43000:43000
      options: --entrypoint /bin/bash

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Download Bitcoin Testnet app binary
        uses: actions/download-artifact@v2
        with:
          name: bitcoin-testnet-app
          path: bin

      - name: Run tests
        run: |
          cd tests && pip install -r requirements.txt && PYTHONPATH=$PYTHONPATH:/speculos pytest


  job_test_legacy_native:
    name: Legacy tests
    needs: job_build
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/speculos:latest
      ports:
        - 1234:1234
        - 9999:9999
        - 40000:40000
        - 41000:41000
        - 42000:42000
        - 43000:43000
      options: --entrypoint /bin/bash

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Download Bitcoin Testnet app binary
        uses: actions/download-artifact@v2
        with:
          name: bitcoin-testnet-app
          path: tests-legacy/bitcoin-testnet-bin

      - name: Run tests
        run: |
          cd tests-legacy && pip install -r requirements.txt && PATH=$PATH:/speculos pytest


  job_test_legacy_lib:
    name: Legacy tests (library)
    needs: job_build
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/speculos:latest
      ports:
        - 1234:1234
        - 9999:9999
        - 40000:40000
        - 41000:41000
        - 42000:42000
        - 43000:43000
      options: --entrypoint /bin/bash

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Download Bitcoin app binary
        uses: actions/download-artifact@v2
        with:
          name: bitcoin-app
          path: tests-legacy/bitcoin-bin

      - name: Download Bitcoin Testnet app binary (library version)
        uses: actions/download-artifact@v2
        with:
          name: bitcoin-testnet-lib-app
          path: tests-legacy/bitcoin-testnet-bin


      - name: Run tests
        run: |
          cd tests-legacy && pip install -r requirements.txt && PATH=$PATH:/speculos pytest
